### ISSUE TITLE
Mohammad Reza Pahlavi's change of the solar calendar

### ISSUE THREAD

**Issue by florisre** [theodore-s-beers/muqawwim#194]
> In 1976, Shah [Mohammad Reza Pahlavi](https://en.wikipedia.org/wiki/Mohammad_Reza_Pahlavi) changed the origin of the calendar to the beginning of [Cyrus the Great](https://en.wikipedia.org/wiki/Cyrus_the_Great)'s reign as its first year, rather than the [Hijra](https://en.wikipedia.org/wiki/Hegira) of [Muhammad](https://en.wikipedia.org/wiki/Muhammad). Overnight, the year changed from 1355 to 2535. This change only lasted until the [Iranian revolution](https://en.wikipedia.org/wiki/Iranian_revolution) in 1979, at which time the calendar reverted to Solar Hijri.[[8]](https://en.wikipedia.org/wiki/Iranian_calendars#cite_note-8)

I came across a date in this specific calendar and thought it might be a neat addition to your tool. And also a quick one, as it simply changes the year in the Iranian Hijri calendar. The sentence above is taken from https://en.wikipedia.org/wiki/Iranian_calendars.

**Comment by theodore-s-beers** [comment]
Thanks! Will add it to the list.

**Comment by theodore-s-beers** [comment]
Implemented in #205
